table 'Vocabulary & Notes'
	lineageTag: 4761b136-76ca-44f6-9d05-9e188102411b

	column '📖  Data Dictionary & Vocabulary  |  FP20 Analytics Procurement Challenge'
		dataType: string
		lineageTag: 8a1f76ca-d323-4c03-93fe-5d90ef4cc1aa
		summarizeBy: none
		sourceColumn: 📖  Data Dictionary & Vocabulary  |  FP20 Analytics Procurement Challenge

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 969b8291-4136-46e8-8cc2-d1e603cbb6e5
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: c079e8fc-4af2-47c7-beb5-1c0877af4b6c
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: 4c436969-bdfb-4541-ba15-a3dd035204c1
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		lineageTag: 90ab80f4-046c-4bab-b37c-fdc954f641f7
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	column Column6
		dataType: string
		lineageTag: 8bd01489-0b26-42c3-b89c-9742a2751a03
		summarizeBy: none
		sourceColumn: Column6

		annotation SummarizationSetBy = Automatic

	partition 'Vocabulary & Notes' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("B:\IT & Data\Data\Challenges\FP20 Procurement\FP20_Procurement_C37 Dataset.xlsx"), null, true),
				    #"Vocabulary & Notes_Sheet" = Source{[Item="Vocabulary & Notes",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Vocabulary & Notes_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"📖  Data Dictionary & Vocabulary  |  FP20 Analytics Procurement Challenge", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type any}, {"Column5", type text}, {"Column6", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

